### ISSUE TITLE
Can't run update and lookup at  the same time

### ISSUE THREAD

**Issue by 1v4n4** [fixthestatusquo/lookup-lc#7]
We use Level DB for lookup. The problem is - two processes can't access it.
Processes:
- Lookup - can run any time
- Update database -  once a day.

How to solve this?

**Comment by 1v4n4** [comment]
I put a 3-minute timeout for the lookup() if it is around update time (00:00), just to illustrate the problem.

One possible solution could be to make a duplicate DB (it contains 80k of hashes, so nothing heavy), and use it for lookups. Still, there would be one very small piece of time when a copy is replaced with a new database and if lookup is run at the same time, it will not be successful. 

@tttp ideas welcome

**Comment by 1v4n4** [comment]
The second, minor, issue:

We have key-value pairs in LevelDB, and for hashes, we need only keys. So what should I put as a value? I used {email: null} as a value so far, but that is just a random thing, doesn't mean anything.  Is there any hash info we could use?

And no, we can not have an empty value.

**Comment by tttp** [comment]
Hi,

- these could be the same process, then they should be able to access at the same time (and the update would pause the lookups)
- we don't have to use levelDB, we can use sqlite or cloudflare KV or anything else ;)
- this being said, doing a full update while being able to lookup is tricky, you need to be able to check if an email exists in the list, your code doesn't remove hashes that were removed in the CRM, 

keep in mind that updating the full list does take way less than half a second (it's supposed to do at least 400k writes per second) once the list has been fetched (ie when we need to be sure no lookups happen

Two options:
## in place updating
- you need to change the algorithm to be able to remove old hashes that were deleted on the crm 
- you need to be able to run the update as a separate thread within the same process

## replace db
- this is the option you mentioned, switch between two dbs (say lc-1 and lc-2), say you are on the day when lc-1 is active, you update lc-2, then switch

**Comment by tttp** [comment]
so #10 and #11 will fix it:

1. index.js (missing in repo) contains two http endpoint to lookup (existing) and update (new)
I can't give specific examples/implementation as the index.js is missing, but say it's

http.get /fetch -> does a lookup
http.post /update -> does a fetch

update is triggered by cronjob OR by curl  -X POST http:/localhost:xyz/update
(the later for dev/fix)

so no problem accessing leveldb on both fetch and lookup, as it's the same process

and we go for update in place, with delete everything in the db and write them all (it should take a few ms, it's fine)
